#Don't Change this
versionNumber: 2.1


# Amount of cars to buy (resets on lunch) 0 = no limit
AmountOFCars: 0

#This is how often to check game state don't change unless you know what you're doing
UpdateINT: 1800

#Display 1080p Min Only
Display: 1

#Change in AH delay noticed when pressing the y menu button
#Change this if you notice it's too slow at opening the buy menu or too fast
Delay: 400

#Capture images for money
UnpdateImagesMoney: true
#In sec how many times to check your money
MoneyTime: 300
#When you hit lower then $1k quit buying cars
#This might not be 100% accurate
Moneylimits: 
  Limitmoney: false
  MoneyLimit: 1000

#Check When you change tabs to stop keyboard Input
CheckGameSelected: true


